Remove dangling comma in esm/package.json
It breaks rollup, e.g

```
[!] (plugin commonjs) SyntaxError: Unexpected token } in JSON at position 102
SyntaxError: Unexpected token } in JSON at position 102
    at JSON.parse (<anonymous>)
```